SET C51INC=C:\Keil_v5\C51\Inc;C:\Keil_v5\C51\Inc\SOC
SET C51LIB=C:\Keil_v5\C51\Lib
SET CPU_TYPE=SC92F7323
SET CPU_VENDOR=SC92Fxx Series
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x016E3600
"C:\Keil_v5\C51\BIN\A51.EXE" @"STARTUP._ia"
"C:\Keil_v5\C51\BIN\C51.EXE" @"main.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @"ADC_Init.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @"BTM.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @"EX_Init.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @"IAP_Init.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @"IO_Init.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @"TIMER_~1.__I"
"C:\Keil_v5\C51\BIN\C51.EXE" @"UART_I~1.__I"
"C:\Keil_v5\C51\BIN\C51.EXE" @"PWM_Init.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @"LCD_Init.__i"
"C:\Keil_v5\C51\BIN\BL51.EXE" @"FULLRE~1.LNP"
"C:\Keil_v5\C51\BIN\OH51.EXE" "FullResources" 
